import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReactQueryProviders from '@/hooks/useReactQuery'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '꿀차장 - 꿀꿀',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <head>
        <meta name="application-name" content="꿀차" />
        <meta name="apple-mobile-web-app-title" content="꿀차" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </head>
      <body className={inter.className}>
        <div id="root" className={`flex justify-center `}>
          <div
            className=" w-full  max-w-[768px]  rounded-lg bg-gradient-to-r from-blue-200 via-purple-200 to-pink-100 p-4 shadow-lg"
            style={{ minHeight: '100vh' }}
          >
            <div id="layer1" className={`relative z-100 flex flex-1 flex-col overflow-hidden`}>
              <ReactQueryProviders>{children}</ReactQueryProviders>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
